### ISSUE TITLE
parsing fails

### ISSUE THREAD

**Issue by fictorial** [sustrik/wsock#1]
Just checking this out a bit and noticed a bug.

I'm connecting to a simple wsock server with wscat from the node.js ws module on npm.

One of the header lines sent is:

    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

but "vend" is looking for the first space in the value for some reason and complains when it finds one:

    permessage-deflate; client_max_window_bits

I took "vend" out and was able to connect.  No PR because obviously it's there for a reason.

**Comment by sustrik** [comment]
For now, I've just removed the checks.

Eventually, the code should remove trailing whitespace as per HTTP spec:

"Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace."

**Comment by sustrik** [comment]
The whitespace is not handled correctly.
